name: "🐞 Bug report"
description: "Reporte um problema encontrado no ClassHero"
title: "[Bug] "
labels:
  - "type:bug"
  - "status:needs-info"
body:
  - type: checkboxes
    id: checks
    attributes:
      label: "Confirmações"
      description: "Antes de enviar, confirme:"
      options:
        - label: "Procurei por issues semelhantes"
          required: true
        - label: "Reproduzi o problema pelo menos 1–2 vezes"
          required: true

  - type: input
    id: summary
    attributes:
      label: "Resumo do problema (1 linha)"
      placeholder: "Login — código não chega no mobile (iOS 17)"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Passos para reproduzir"
      description: "Liste os passos numerados."
      placeholder: |
        1) Acessar ...
        2) Clicar em ...
        3) Observar ...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Comportamento esperado"
      placeholder: "O que você esperava que acontecesse?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Comportamento atual"
      description: "Inclua mensagens de erro visíveis na tela, se houver."
      placeholder: "O que aconteceu de fato?"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severidade"
      options:
        - "bloqueante"
        - "alta"
        - "média"
        - "baixa"
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: "Reprodutibilidade"
      options:
        - "sempre"
        - "frequentemente"
        - "às vezes"
        - "raramente"
        - "não reproduzi novamente"

  - type: input
    id: area
    attributes:
      label: "Área/funcionalidade"
      placeholder: "frontend, backend, nestjs, supabase, quiz, assignments, timeline, rewards"

  - type: input
    id: route
    attributes:
      label: "Tela/rota (se aplicável)"
      placeholder: "/home/theme-materials"

  - type: input
    id: user_role
    attributes:
      label: "Papel do usuário"
      placeholder: "estudante / professor / admin"

  - type: dropdown
    id: auth
    attributes:
      label: "Autenticação"
      options:
        - "código por e-mail"
        - "senha"
        - "não autenticado"
        - "outro"

  - type: input
    id: version
    attributes:
      label: "Versão/build (se souber)"
      placeholder: "tag, hash do commit ou data/hora"

  - type: input
    id: environment
    attributes:
      label: "Ambiente"
      placeholder: "iPhone 13 iOS 17.5 / Chrome 126 no macOS 14 / Android 14 app"

  - type: textarea
    id: evidence
    attributes:
      label: "Evidências"
      description: "Arraste e solte prints, vídeos curtos e trechos de log (anonimizados)."

  - type: textarea
    id: notes
    attributes:
      label: "Observações adicionais"
      placeholder: "Qualquer detalhe que ajude na triagem."
