blank_issues_enabled: false
contact_links:
  - name: "❓ Dúvidas gerais (Discussions)"
    url: "https://github.com/evertonfoz/classhero-tracker/discussions"
    about: "Perguntas que não são bugs ou melhorias."
